# dapr/spec

trigger:
  - master

pr : none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseNode@1
  inputs:
    version: '10.16.3'
- task: Bash@3
  displayName: 'Install md-to-pdf'
  inputs:
    targetType: 'inline'
    script: |
      npm install -g md-to-pdf
    workingDirectory: '$(Build.SourcesDirectory)'
- task: Bash@3
  displayName: 'Create pdf output directory'
  inputs:
    targetType: 'inline'
    script: |
      mkdir ./output_pdf
      mkdir ./output_md
    workingDirectory: '$(Build.SourcesDirectory)'
- task: Bash@3
  displayName: 'Generate PDF files'
  inputs:
    targetType: 'inline'
    script: |
      echo Copying *.md to ./output_md/
      cp *.md ./output_md/
      
      pushd ./output_md

      rm -f README.md CONTRIBUTING.md

      echo Genereating PDFs from markdown documents
      for filename in *.md; do
        md-to-pdf $filename ../output_pdf/$(basename $filename .md).pdf
      done

      popd
    workingDirectory: '$(Build.SourcesDirectory)'
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)/output_pdf/'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/dapr-spec-pdf.zip'
    replaceExistingArchive: true
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)/output_md/'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/dapr-spec-md.zip'
    replaceExistingArchive: true
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'